# Generated by Django 4.2 on 2023-04-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='base_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
